spring.application.name=graphql-playground

#graphql
#schema file path address
spring.graphql.schema.locations=classpath:graphql/lec09
# end point
spring.graphql.path=/graphql

#graphiql: User interface, user interact with graphql endpoints
spring.graphql.graphiql.enabled=true
#expose public
spring.graphql.graphiql.path=/graphiql